# Shared interactive zsh settings for Linux and macOS.

alias vim='nvim'
alias vi='nvim'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

export LS_COLORS='di=1;34:ln=1;35:so=1;32:pi=1;33:ex=1;31:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43'

# Reuse completion initialization from the user's existing .zshrc, if present.
if (( ! ${+functions[compdef]} )); then
    autoload -Uz compinit && compinit
fi
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

autoload -Uz colors && colors
setopt PROMPT_SUBST
PROMPT='%F{green}%n@%m%f %F{cyan}%~%f %# '

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
